// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'AIzaSyCKLliFDFNtWv8XxbxkIIFaT2z4J2V1v0c',
    appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '1:718796753680:web:fb2e11bfee3f2bcefbf395',
    messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '718796753680',
    projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? 'fruit-app-33df1',
    authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ?? 'fruit-app-33df1.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? 'fruit-app-33df1.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? 'AIzaSyDz4zD3FZVibHQk_xV406MjQzQHhBoLtEo',
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '1:718796753680:android:022165c940dbbebefbf395',
    messagingSenderId: dotenv.env['FIREBASE_ANDROID_MESSAGING_SENDER_ID'] ?? '718796753680',
    projectId: dotenv.env['FIREBASE_ANDROID_PROJECT_ID'] ?? 'fruit-app-33df1',
    storageBucket: dotenv.env['FIREBASE_ANDROID_STORAGE_BUCKET'] ?? 'fruit-app-33df1.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyBKJAyjJxFKWdcgSfoPEcy-Caaa65dKUBg',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:718796753680:ios:4b35ecb59deb3945fbf395',
    messagingSenderId: dotenv.env['FIREBASE_IOS_MESSAGING_SENDER_ID'] ?? '718796753680',
    projectId: dotenv.env['FIREBASE_IOS_PROJECT_ID'] ?? 'fruit-app-33df1',
    storageBucket: dotenv.env['FIREBASE_IOS_STORAGE_BUCKET'] ?? 'fruit-app-33df1.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.example.fruithub',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyBKJAyjJxFKWdcgSfoPEcy-Caaa65dKUBg',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:718796753680:ios:4b35ecb59deb3945fbf395',
    messagingSenderId: dotenv.env['FIREBASE_IOS_MESSAGING_SENDER_ID'] ?? '718796753680',
    projectId: dotenv.env['FIREBASE_IOS_PROJECT_ID'] ?? 'fruit-app-33df1',
    storageBucket: dotenv.env['FIREBASE_IOS_STORAGE_BUCKET'] ?? 'fruit-app-33df1.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.example.fruithub',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? 'AIzaSyCKLliFDFNtWv8XxbxkIIFaT2z4J2V1v0c',
    appId: dotenv.env['FIREBASE_WINDOWS_APP_ID'] ?? '1:718796753680:web:187efc4ef801b05afbf395',
    messagingSenderId: dotenv.env['FIREBASE_WINDOWS_MESSAGING_SENDER_ID'] ?? '718796753680',
    projectId: dotenv.env['FIREBASE_WINDOWS_PROJECT_ID'] ?? 'fruit-app-33df1',
    authDomain: dotenv.env['FIREBASE_WINDOWS_AUTH_DOMAIN'] ?? 'fruit-app-33df1.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_WINDOWS_STORAGE_BUCKET'] ?? 'fruit-app-33df1.firebasestorage.app',
  );
}
