// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLliFDFNtWv8XxbxkIIFaT2z4J2V1v0c',
    appId: '1:718796753680:web:fb2e11bfee3f2bcefbf395',
    messagingSenderId: '718796753680',
    projectId: 'fruit-app-33df1',
    authDomain: 'fruit-app-33df1.firebaseapp.com',
    storageBucket: 'fruit-app-33df1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4zD3FZVibHQk_xV406MjQzQHhBoLtEo',
    appId: '1:718796753680:android:022165c940dbbebefbf395',
    messagingSenderId: '718796753680',
    projectId: 'fruit-app-33df1',
    storageBucket: 'fruit-app-33df1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKJAyjJxFKWdcgSfoPEcy-Caaa65dKUBg',
    appId: '1:718796753680:ios:4b35ecb59deb3945fbf395',
    messagingSenderId: '718796753680',
    projectId: 'fruit-app-33df1',
    storageBucket: 'fruit-app-33df1.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKJAyjJxFKWdcgSfoPEcy-Caaa65dKUBg',
    appId: '1:718796753680:ios:4b35ecb59deb3945fbf395',
    messagingSenderId: '718796753680',
    projectId: 'fruit-app-33df1',
    storageBucket: 'fruit-app-33df1.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKLliFDFNtWv8XxbxkIIFaT2z4J2V1v0c',
    appId: '1:718796753680:web:187efc4ef801b05afbf395',
    messagingSenderId: '718796753680',
    projectId: 'fruit-app-33df1',
    authDomain: 'fruit-app-33df1.firebaseapp.com',
    storageBucket: 'fruit-app-33df1.firebasestorage.app',
  );
}
